// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_msgheader.proto

#ifndef PROTOBUF_gateway_5fmsgheader_2eproto__INCLUDED
#define PROTOBUF_gateway_5fmsgheader_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace gateway_proto {
class CreateRoleRequest;
class CreateRoleRequestDefaultTypeInternal;
extern CreateRoleRequestDefaultTypeInternal _CreateRoleRequest_default_instance_;
class CreateRoleResponse;
class CreateRoleResponseDefaultTypeInternal;
extern CreateRoleResponseDefaultTypeInternal _CreateRoleResponse_default_instance_;
class RoleLoginRequest;
class RoleLoginRequestDefaultTypeInternal;
extern RoleLoginRequestDefaultTypeInternal _RoleLoginRequest_default_instance_;
class RoleLoginResponse;
class RoleLoginResponseDefaultTypeInternal;
extern RoleLoginResponseDefaultTypeInternal _RoleLoginResponse_default_instance_;
}  // namespace gateway_proto

namespace gateway_proto {

namespace protobuf_gateway_5fmsgheader_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gateway_5fmsgheader_2eproto

// ===================================================================

class RoleLoginRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gateway_proto.RoleLoginRequest) */ {
 public:
  RoleLoginRequest();
  virtual ~RoleLoginRequest();

  RoleLoginRequest(const RoleLoginRequest& from);

  inline RoleLoginRequest& operator=(const RoleLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoleLoginRequest& default_instance();

  static inline const RoleLoginRequest* internal_default_instance() {
    return reinterpret_cast<const RoleLoginRequest*>(
               &_RoleLoginRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RoleLoginRequest* other);

  // implements Message ----------------------------------------------

  inline RoleLoginRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RoleLoginRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoleLoginRequest& from);
  void MergeFrom(const RoleLoginRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoleLoginRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string platomId = 2;
  void clear_platomid();
  static const int kPlatomIdFieldNumber = 2;
  const ::std::string& platomid() const;
  void set_platomid(const ::std::string& value);
  #if LANG_CXX11
  void set_platomid(::std::string&& value);
  #endif
  void set_platomid(const char* value);
  void set_platomid(const char* value, size_t size);
  ::std::string* mutable_platomid();
  ::std::string* release_platomid();
  void set_allocated_platomid(::std::string* platomid);

  // string userName = 3;
  void clear_username();
  static const int kUserNameFieldNumber = 3;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // int32 sdkId = 1;
  void clear_sdkid();
  static const int kSdkIdFieldNumber = 1;
  ::google::protobuf::int32 sdkid() const;
  void set_sdkid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gateway_proto.RoleLoginRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr platomid_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::int32 sdkid_;
  mutable int _cached_size_;
  friend struct protobuf_gateway_5fmsgheader_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoleLoginResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gateway_proto.RoleLoginResponse) */ {
 public:
  RoleLoginResponse();
  virtual ~RoleLoginResponse();

  RoleLoginResponse(const RoleLoginResponse& from);

  inline RoleLoginResponse& operator=(const RoleLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoleLoginResponse& default_instance();

  static inline const RoleLoginResponse* internal_default_instance() {
    return reinterpret_cast<const RoleLoginResponse*>(
               &_RoleLoginResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(RoleLoginResponse* other);

  // implements Message ----------------------------------------------

  inline RoleLoginResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  RoleLoginResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoleLoginResponse& from);
  void MergeFrom(const RoleLoginResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoleLoginResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string address = 4;
  void clear_address();
  static const int kAddressFieldNumber = 4;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // string key = 5;
  void clear_key();
  static const int kKeyFieldNumber = 5;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string msg = 6;
  void clear_msg();
  static const int kMsgFieldNumber = 6;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 port = 1;
  void clear_port();
  static const int kPortFieldNumber = 1;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // int32 rid = 2;
  void clear_rid();
  static const int kRidFieldNumber = 2;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 status = 3;
  void clear_status();
  static const int kStatusFieldNumber = 3;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gateway_proto.RoleLoginResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 status_;
  mutable int _cached_size_;
  friend struct protobuf_gateway_5fmsgheader_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateRoleRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gateway_proto.CreateRoleRequest) */ {
 public:
  CreateRoleRequest();
  virtual ~CreateRoleRequest();

  CreateRoleRequest(const CreateRoleRequest& from);

  inline CreateRoleRequest& operator=(const CreateRoleRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateRoleRequest& default_instance();

  static inline const CreateRoleRequest* internal_default_instance() {
    return reinterpret_cast<const CreateRoleRequest*>(
               &_CreateRoleRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(CreateRoleRequest* other);

  // implements Message ----------------------------------------------

  inline CreateRoleRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  CreateRoleRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CreateRoleRequest& from);
  void MergeFrom(const CreateRoleRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CreateRoleRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string platomId = 2;
  void clear_platomid();
  static const int kPlatomIdFieldNumber = 2;
  const ::std::string& platomid() const;
  void set_platomid(const ::std::string& value);
  #if LANG_CXX11
  void set_platomid(::std::string&& value);
  #endif
  void set_platomid(const char* value);
  void set_platomid(const char* value, size_t size);
  ::std::string* mutable_platomid();
  ::std::string* release_platomid();
  void set_allocated_platomid(::std::string* platomid);

  // string userName = 3;
  void clear_username();
  static const int kUserNameFieldNumber = 3;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // int32 sdkId = 1;
  void clear_sdkid();
  static const int kSdkIdFieldNumber = 1;
  ::google::protobuf::int32 sdkid() const;
  void set_sdkid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gateway_proto.CreateRoleRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr platomid_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::int32 sdkid_;
  mutable int _cached_size_;
  friend struct protobuf_gateway_5fmsgheader_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateRoleResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gateway_proto.CreateRoleResponse) */ {
 public:
  CreateRoleResponse();
  virtual ~CreateRoleResponse();

  CreateRoleResponse(const CreateRoleResponse& from);

  inline CreateRoleResponse& operator=(const CreateRoleResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateRoleResponse& default_instance();

  static inline const CreateRoleResponse* internal_default_instance() {
    return reinterpret_cast<const CreateRoleResponse*>(
               &_CreateRoleResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(CreateRoleResponse* other);

  // implements Message ----------------------------------------------

  inline CreateRoleResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  CreateRoleResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CreateRoleResponse& from);
  void MergeFrom(const CreateRoleResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CreateRoleResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string address = 4;
  void clear_address();
  static const int kAddressFieldNumber = 4;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // string key = 5;
  void clear_key();
  static const int kKeyFieldNumber = 5;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string msg = 6;
  void clear_msg();
  static const int kMsgFieldNumber = 6;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 port = 1;
  void clear_port();
  static const int kPortFieldNumber = 1;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // int32 rid = 2;
  void clear_rid();
  static const int kRidFieldNumber = 2;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 status = 3;
  void clear_status();
  static const int kStatusFieldNumber = 3;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gateway_proto.CreateRoleResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 status_;
  mutable int _cached_size_;
  friend struct protobuf_gateway_5fmsgheader_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RoleLoginRequest

// int32 sdkId = 1;
inline void RoleLoginRequest::clear_sdkid() {
  sdkid_ = 0;
}
inline ::google::protobuf::int32 RoleLoginRequest::sdkid() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginRequest.sdkId)
  return sdkid_;
}
inline void RoleLoginRequest::set_sdkid(::google::protobuf::int32 value) {
  
  sdkid_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginRequest.sdkId)
}

// string platomId = 2;
inline void RoleLoginRequest::clear_platomid() {
  platomid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoleLoginRequest::platomid() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginRequest.platomId)
  return platomid_.GetNoArena();
}
inline void RoleLoginRequest::set_platomid(const ::std::string& value) {
  
  platomid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginRequest.platomId)
}
#if LANG_CXX11
inline void RoleLoginRequest::set_platomid(::std::string&& value) {
  
  platomid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.RoleLoginRequest.platomId)
}
#endif
inline void RoleLoginRequest::set_platomid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  platomid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.RoleLoginRequest.platomId)
}
inline void RoleLoginRequest::set_platomid(const char* value, size_t size) {
  
  platomid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.RoleLoginRequest.platomId)
}
inline ::std::string* RoleLoginRequest::mutable_platomid() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.RoleLoginRequest.platomId)
  return platomid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoleLoginRequest::release_platomid() {
  // @@protoc_insertion_point(field_release:gateway_proto.RoleLoginRequest.platomId)
  
  return platomid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoleLoginRequest::set_allocated_platomid(::std::string* platomid) {
  if (platomid != NULL) {
    
  } else {
    
  }
  platomid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), platomid);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.RoleLoginRequest.platomId)
}

// string userName = 3;
inline void RoleLoginRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoleLoginRequest::username() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginRequest.userName)
  return username_.GetNoArena();
}
inline void RoleLoginRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginRequest.userName)
}
#if LANG_CXX11
inline void RoleLoginRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.RoleLoginRequest.userName)
}
#endif
inline void RoleLoginRequest::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.RoleLoginRequest.userName)
}
inline void RoleLoginRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.RoleLoginRequest.userName)
}
inline ::std::string* RoleLoginRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.RoleLoginRequest.userName)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoleLoginRequest::release_username() {
  // @@protoc_insertion_point(field_release:gateway_proto.RoleLoginRequest.userName)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoleLoginRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.RoleLoginRequest.userName)
}

// -------------------------------------------------------------------

// RoleLoginResponse

// int32 port = 1;
inline void RoleLoginResponse::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 RoleLoginResponse::port() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginResponse.port)
  return port_;
}
inline void RoleLoginResponse::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginResponse.port)
}

// int32 rid = 2;
inline void RoleLoginResponse::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 RoleLoginResponse::rid() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginResponse.rid)
  return rid_;
}
inline void RoleLoginResponse::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginResponse.rid)
}

// int32 status = 3;
inline void RoleLoginResponse::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 RoleLoginResponse::status() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginResponse.status)
  return status_;
}
inline void RoleLoginResponse::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginResponse.status)
}

// string address = 4;
inline void RoleLoginResponse::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoleLoginResponse::address() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginResponse.address)
  return address_.GetNoArena();
}
inline void RoleLoginResponse::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginResponse.address)
}
#if LANG_CXX11
inline void RoleLoginResponse::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.RoleLoginResponse.address)
}
#endif
inline void RoleLoginResponse::set_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.RoleLoginResponse.address)
}
inline void RoleLoginResponse::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.RoleLoginResponse.address)
}
inline ::std::string* RoleLoginResponse::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.RoleLoginResponse.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoleLoginResponse::release_address() {
  // @@protoc_insertion_point(field_release:gateway_proto.RoleLoginResponse.address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoleLoginResponse::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.RoleLoginResponse.address)
}

// string key = 5;
inline void RoleLoginResponse::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoleLoginResponse::key() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginResponse.key)
  return key_.GetNoArena();
}
inline void RoleLoginResponse::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginResponse.key)
}
#if LANG_CXX11
inline void RoleLoginResponse::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.RoleLoginResponse.key)
}
#endif
inline void RoleLoginResponse::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.RoleLoginResponse.key)
}
inline void RoleLoginResponse::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.RoleLoginResponse.key)
}
inline ::std::string* RoleLoginResponse::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.RoleLoginResponse.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoleLoginResponse::release_key() {
  // @@protoc_insertion_point(field_release:gateway_proto.RoleLoginResponse.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoleLoginResponse::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.RoleLoginResponse.key)
}

// string msg = 6;
inline void RoleLoginResponse::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoleLoginResponse::msg() const {
  // @@protoc_insertion_point(field_get:gateway_proto.RoleLoginResponse.msg)
  return msg_.GetNoArena();
}
inline void RoleLoginResponse::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.RoleLoginResponse.msg)
}
#if LANG_CXX11
inline void RoleLoginResponse::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.RoleLoginResponse.msg)
}
#endif
inline void RoleLoginResponse::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.RoleLoginResponse.msg)
}
inline void RoleLoginResponse::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.RoleLoginResponse.msg)
}
inline ::std::string* RoleLoginResponse::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.RoleLoginResponse.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoleLoginResponse::release_msg() {
  // @@protoc_insertion_point(field_release:gateway_proto.RoleLoginResponse.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoleLoginResponse::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.RoleLoginResponse.msg)
}

// -------------------------------------------------------------------

// CreateRoleRequest

// int32 sdkId = 1;
inline void CreateRoleRequest::clear_sdkid() {
  sdkid_ = 0;
}
inline ::google::protobuf::int32 CreateRoleRequest::sdkid() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleRequest.sdkId)
  return sdkid_;
}
inline void CreateRoleRequest::set_sdkid(::google::protobuf::int32 value) {
  
  sdkid_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleRequest.sdkId)
}

// string platomId = 2;
inline void CreateRoleRequest::clear_platomid() {
  platomid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRoleRequest::platomid() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleRequest.platomId)
  return platomid_.GetNoArena();
}
inline void CreateRoleRequest::set_platomid(const ::std::string& value) {
  
  platomid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleRequest.platomId)
}
#if LANG_CXX11
inline void CreateRoleRequest::set_platomid(::std::string&& value) {
  
  platomid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.CreateRoleRequest.platomId)
}
#endif
inline void CreateRoleRequest::set_platomid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  platomid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.CreateRoleRequest.platomId)
}
inline void CreateRoleRequest::set_platomid(const char* value, size_t size) {
  
  platomid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.CreateRoleRequest.platomId)
}
inline ::std::string* CreateRoleRequest::mutable_platomid() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.CreateRoleRequest.platomId)
  return platomid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRoleRequest::release_platomid() {
  // @@protoc_insertion_point(field_release:gateway_proto.CreateRoleRequest.platomId)
  
  return platomid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRoleRequest::set_allocated_platomid(::std::string* platomid) {
  if (platomid != NULL) {
    
  } else {
    
  }
  platomid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), platomid);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.CreateRoleRequest.platomId)
}

// string userName = 3;
inline void CreateRoleRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRoleRequest::username() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleRequest.userName)
  return username_.GetNoArena();
}
inline void CreateRoleRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleRequest.userName)
}
#if LANG_CXX11
inline void CreateRoleRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.CreateRoleRequest.userName)
}
#endif
inline void CreateRoleRequest::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.CreateRoleRequest.userName)
}
inline void CreateRoleRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.CreateRoleRequest.userName)
}
inline ::std::string* CreateRoleRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.CreateRoleRequest.userName)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRoleRequest::release_username() {
  // @@protoc_insertion_point(field_release:gateway_proto.CreateRoleRequest.userName)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRoleRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.CreateRoleRequest.userName)
}

// -------------------------------------------------------------------

// CreateRoleResponse

// int32 port = 1;
inline void CreateRoleResponse::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 CreateRoleResponse::port() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleResponse.port)
  return port_;
}
inline void CreateRoleResponse::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleResponse.port)
}

// int32 rid = 2;
inline void CreateRoleResponse::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 CreateRoleResponse::rid() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleResponse.rid)
  return rid_;
}
inline void CreateRoleResponse::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleResponse.rid)
}

// int32 status = 3;
inline void CreateRoleResponse::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 CreateRoleResponse::status() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleResponse.status)
  return status_;
}
inline void CreateRoleResponse::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleResponse.status)
}

// string address = 4;
inline void CreateRoleResponse::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRoleResponse::address() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleResponse.address)
  return address_.GetNoArena();
}
inline void CreateRoleResponse::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleResponse.address)
}
#if LANG_CXX11
inline void CreateRoleResponse::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.CreateRoleResponse.address)
}
#endif
inline void CreateRoleResponse::set_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.CreateRoleResponse.address)
}
inline void CreateRoleResponse::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.CreateRoleResponse.address)
}
inline ::std::string* CreateRoleResponse::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.CreateRoleResponse.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRoleResponse::release_address() {
  // @@protoc_insertion_point(field_release:gateway_proto.CreateRoleResponse.address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRoleResponse::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.CreateRoleResponse.address)
}

// string key = 5;
inline void CreateRoleResponse::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRoleResponse::key() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleResponse.key)
  return key_.GetNoArena();
}
inline void CreateRoleResponse::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleResponse.key)
}
#if LANG_CXX11
inline void CreateRoleResponse::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.CreateRoleResponse.key)
}
#endif
inline void CreateRoleResponse::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.CreateRoleResponse.key)
}
inline void CreateRoleResponse::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.CreateRoleResponse.key)
}
inline ::std::string* CreateRoleResponse::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.CreateRoleResponse.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRoleResponse::release_key() {
  // @@protoc_insertion_point(field_release:gateway_proto.CreateRoleResponse.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRoleResponse::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.CreateRoleResponse.key)
}

// string msg = 6;
inline void CreateRoleResponse::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRoleResponse::msg() const {
  // @@protoc_insertion_point(field_get:gateway_proto.CreateRoleResponse.msg)
  return msg_.GetNoArena();
}
inline void CreateRoleResponse::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gateway_proto.CreateRoleResponse.msg)
}
#if LANG_CXX11
inline void CreateRoleResponse::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gateway_proto.CreateRoleResponse.msg)
}
#endif
inline void CreateRoleResponse::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gateway_proto.CreateRoleResponse.msg)
}
inline void CreateRoleResponse::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gateway_proto.CreateRoleResponse.msg)
}
inline ::std::string* CreateRoleResponse::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:gateway_proto.CreateRoleResponse.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRoleResponse::release_msg() {
  // @@protoc_insertion_point(field_release:gateway_proto.CreateRoleResponse.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRoleResponse::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:gateway_proto.CreateRoleResponse.msg)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace gateway_proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gateway_5fmsgheader_2eproto__INCLUDED
