// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgheader.proto

#ifndef PROTOBUF_msgheader_2eproto__INCLUDED
#define PROTOBUF_msgheader_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace msghandle {
class MessageHeader1;
class MessageHeader1DefaultTypeInternal;
extern MessageHeader1DefaultTypeInternal _MessageHeader1_default_instance_;
}  // namespace msghandle

namespace msghandle {

namespace protobuf_msgheader_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msgheader_2eproto

// ===================================================================

class MessageHeader1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msghandle.MessageHeader1) */ {
 public:
  MessageHeader1();
  virtual ~MessageHeader1();

  MessageHeader1(const MessageHeader1& from);

  inline MessageHeader1& operator=(const MessageHeader1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageHeader1& default_instance();

  static inline const MessageHeader1* internal_default_instance() {
    return reinterpret_cast<const MessageHeader1*>(
               &_MessageHeader1_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MessageHeader1* other);

  // implements Message ----------------------------------------------

  inline MessageHeader1* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageHeader1* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageHeader1& from);
  void MergeFrom(const MessageHeader1& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageHeader1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 msg_type = 1;
  void clear_msg_type();
  static const int kMsgTypeFieldNumber = 1;
  ::google::protobuf::int32 msg_type() const;
  void set_msg_type(::google::protobuf::int32 value);

  // int32 msg_size = 2;
  void clear_msg_size();
  static const int kMsgSizeFieldNumber = 2;
  ::google::protobuf::int32 msg_size() const;
  void set_msg_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msghandle.MessageHeader1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 msg_type_;
  ::google::protobuf::int32 msg_size_;
  mutable int _cached_size_;
  friend struct protobuf_msgheader_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageHeader1

// int32 msg_type = 1;
inline void MessageHeader1::clear_msg_type() {
  msg_type_ = 0;
}
inline ::google::protobuf::int32 MessageHeader1::msg_type() const {
  // @@protoc_insertion_point(field_get:msghandle.MessageHeader1.msg_type)
  return msg_type_;
}
inline void MessageHeader1::set_msg_type(::google::protobuf::int32 value) {
  
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:msghandle.MessageHeader1.msg_type)
}

// int32 msg_size = 2;
inline void MessageHeader1::clear_msg_size() {
  msg_size_ = 0;
}
inline ::google::protobuf::int32 MessageHeader1::msg_size() const {
  // @@protoc_insertion_point(field_get:msghandle.MessageHeader1.msg_size)
  return msg_size_;
}
inline void MessageHeader1::set_msg_size(::google::protobuf::int32 value) {
  
  msg_size_ = value;
  // @@protoc_insertion_point(field_set:msghandle.MessageHeader1.msg_size)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace msghandle

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgheader_2eproto__INCLUDED
