// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gs_db_ipc.proto

#ifndef PROTOBUF_gs_5fdb_5fipc_2eproto__INCLUDED
#define PROTOBUF_gs_5fdb_5fipc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace inner_ipc {
class FriendItem;
class FriendItemDefaultTypeInternal;
extern FriendItemDefaultTypeInternal _FriendItem_default_instance_;
class LoginInfo;
class LoginInfoDefaultTypeInternal;
extern LoginInfoDefaultTypeInternal _LoginInfo_default_instance_;
class OfflineMsgItem;
class OfflineMsgItemDefaultTypeInternal;
extern OfflineMsgItemDefaultTypeInternal _OfflineMsgItem_default_instance_;
class ReqAddFriendIPC;
class ReqAddFriendIPCDefaultTypeInternal;
extern ReqAddFriendIPCDefaultTypeInternal _ReqAddFriendIPC_default_instance_;
class ReqFriendsIPC;
class ReqFriendsIPCDefaultTypeInternal;
extern ReqFriendsIPCDefaultTypeInternal _ReqFriendsIPC_default_instance_;
class ReqOfflineMsgIPC;
class ReqOfflineMsgIPCDefaultTypeInternal;
extern ReqOfflineMsgIPCDefaultTypeInternal _ReqOfflineMsgIPC_default_instance_;
class ReqRoleInfoIPC;
class ReqRoleInfoIPCDefaultTypeInternal;
extern ReqRoleInfoIPCDefaultTypeInternal _ReqRoleInfoIPC_default_instance_;
class ResAddFriendIPC;
class ResAddFriendIPCDefaultTypeInternal;
extern ResAddFriendIPCDefaultTypeInternal _ResAddFriendIPC_default_instance_;
class ResFriendsIPC;
class ResFriendsIPCDefaultTypeInternal;
extern ResFriendsIPCDefaultTypeInternal _ResFriendsIPC_default_instance_;
class ResOfflineMsgIPC;
class ResOfflineMsgIPCDefaultTypeInternal;
extern ResOfflineMsgIPCDefaultTypeInternal _ResOfflineMsgIPC_default_instance_;
class ResRoleInfoIPC;
class ResRoleInfoIPCDefaultTypeInternal;
extern ResRoleInfoIPCDefaultTypeInternal _ResRoleInfoIPC_default_instance_;
class RoleInfo;
class RoleInfoDefaultTypeInternal;
extern RoleInfoDefaultTypeInternal _RoleInfo_default_instance_;
}  // namespace inner_ipc

namespace inner_ipc {

namespace protobuf_gs_5fdb_5fipc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gs_5fdb_5fipc_2eproto

// ===================================================================

class RoleInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.RoleInfo) */ {
 public:
  RoleInfo();
  virtual ~RoleInfo();

  RoleInfo(const RoleInfo& from);

  inline RoleInfo& operator=(const RoleInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoleInfo& default_instance();

  static inline const RoleInfo* internal_default_instance() {
    return reinterpret_cast<const RoleInfo*>(
               &_RoleInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RoleInfo* other);

  // implements Message ----------------------------------------------

  inline RoleInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  RoleInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoleInfo& from);
  void MergeFrom(const RoleInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoleInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 rid = 2;
  void clear_rid();
  static const int kRidFieldNumber = 2;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.RoleInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 rid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LoginInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.LoginInfo) */ {
 public:
  LoginInfo();
  virtual ~LoginInfo();

  LoginInfo(const LoginInfo& from);

  inline LoginInfo& operator=(const LoginInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginInfo& default_instance();

  static inline const LoginInfo* internal_default_instance() {
    return reinterpret_cast<const LoginInfo*>(
               &_LoginInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LoginInfo* other);

  // implements Message ----------------------------------------------

  inline LoginInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  LoginInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoginInfo& from);
  void MergeFrom(const LoginInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoginInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.LoginInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqRoleInfoIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ReqRoleInfoIPC) */ {
 public:
  ReqRoleInfoIPC();
  virtual ~ReqRoleInfoIPC();

  ReqRoleInfoIPC(const ReqRoleInfoIPC& from);

  inline ReqRoleInfoIPC& operator=(const ReqRoleInfoIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqRoleInfoIPC& default_instance();

  static inline const ReqRoleInfoIPC* internal_default_instance() {
    return reinterpret_cast<const ReqRoleInfoIPC*>(
               &_ReqRoleInfoIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ReqRoleInfoIPC* other);

  // implements Message ----------------------------------------------

  inline ReqRoleInfoIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ReqRoleInfoIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReqRoleInfoIPC& from);
  void MergeFrom(const ReqRoleInfoIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReqRoleInfoIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 2;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // int32 reqrid = 3;
  void clear_reqrid();
  static const int kReqridFieldNumber = 3;
  ::google::protobuf::int32 reqrid() const;
  void set_reqrid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ReqRoleInfoIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  ::google::protobuf::int32 reqrid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResRoleInfoIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ResRoleInfoIPC) */ {
 public:
  ResRoleInfoIPC();
  virtual ~ResRoleInfoIPC();

  ResRoleInfoIPC(const ResRoleInfoIPC& from);

  inline ResRoleInfoIPC& operator=(const ResRoleInfoIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResRoleInfoIPC& default_instance();

  static inline const ResRoleInfoIPC* internal_default_instance() {
    return reinterpret_cast<const ResRoleInfoIPC*>(
               &_ResRoleInfoIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ResRoleInfoIPC* other);

  // implements Message ----------------------------------------------

  inline ResRoleInfoIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ResRoleInfoIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResRoleInfoIPC& from);
  void MergeFrom(const ResRoleInfoIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResRoleInfoIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 5;
  void clear_name();
  static const int kNameFieldNumber = 5;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // .inner_ipc.RoleInfo info = 4;
  bool has_info() const;
  void clear_info();
  static const int kInfoFieldNumber = 4;
  const ::inner_ipc::RoleInfo& info() const;
  ::inner_ipc::RoleInfo* mutable_info();
  ::inner_ipc::RoleInfo* release_info();
  void set_allocated_info(::inner_ipc::RoleInfo* info);

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 2;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // int32 reqrid = 3;
  void clear_reqrid();
  static const int kReqridFieldNumber = 3;
  ::google::protobuf::int32 reqrid() const;
  void set_reqrid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ResRoleInfoIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::inner_ipc::RoleInfo* info_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  ::google::protobuf::int32 reqrid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FriendItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.FriendItem) */ {
 public:
  FriendItem();
  virtual ~FriendItem();

  FriendItem(const FriendItem& from);

  inline FriendItem& operator=(const FriendItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FriendItem& default_instance();

  static inline const FriendItem* internal_default_instance() {
    return reinterpret_cast<const FriendItem*>(
               &_FriendItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(FriendItem* other);

  // implements Message ----------------------------------------------

  inline FriendItem* New() const PROTOBUF_FINAL { return New(NULL); }

  FriendItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FriendItem& from);
  void MergeFrom(const FriendItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FriendItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 4;
  void clear_username();
  static const int kUsernameFieldNumber = 4;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 status = 2;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // int32 timeline = 3;
  void clear_timeline();
  static const int kTimelineFieldNumber = 3;
  ::google::protobuf::int32 timeline() const;
  void set_timeline(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.FriendItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 timeline_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqFriendsIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ReqFriendsIPC) */ {
 public:
  ReqFriendsIPC();
  virtual ~ReqFriendsIPC();

  ReqFriendsIPC(const ReqFriendsIPC& from);

  inline ReqFriendsIPC& operator=(const ReqFriendsIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqFriendsIPC& default_instance();

  static inline const ReqFriendsIPC* internal_default_instance() {
    return reinterpret_cast<const ReqFriendsIPC*>(
               &_ReqFriendsIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ReqFriendsIPC* other);

  // implements Message ----------------------------------------------

  inline ReqFriendsIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ReqFriendsIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReqFriendsIPC& from);
  void MergeFrom(const ReqFriendsIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReqFriendsIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 2;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // int32 type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ReqFriendsIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResFriendsIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ResFriendsIPC) */ {
 public:
  ResFriendsIPC();
  virtual ~ResFriendsIPC();

  ResFriendsIPC(const ResFriendsIPC& from);

  inline ResFriendsIPC& operator=(const ResFriendsIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResFriendsIPC& default_instance();

  static inline const ResFriendsIPC* internal_default_instance() {
    return reinterpret_cast<const ResFriendsIPC*>(
               &_ResFriendsIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ResFriendsIPC* other);

  // implements Message ----------------------------------------------

  inline ResFriendsIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ResFriendsIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResFriendsIPC& from);
  void MergeFrom(const ResFriendsIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResFriendsIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .inner_ipc.FriendItem friends = 3;
  int friends_size() const;
  void clear_friends();
  static const int kFriendsFieldNumber = 3;
  const ::inner_ipc::FriendItem& friends(int index) const;
  ::inner_ipc::FriendItem* mutable_friends(int index);
  ::inner_ipc::FriendItem* add_friends();
  ::google::protobuf::RepeatedPtrField< ::inner_ipc::FriendItem >*
      mutable_friends();
  const ::google::protobuf::RepeatedPtrField< ::inner_ipc::FriendItem >&
      friends() const;

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 2;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ResFriendsIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::inner_ipc::FriendItem > friends_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqAddFriendIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ReqAddFriendIPC) */ {
 public:
  ReqAddFriendIPC();
  virtual ~ReqAddFriendIPC();

  ReqAddFriendIPC(const ReqAddFriendIPC& from);

  inline ReqAddFriendIPC& operator=(const ReqAddFriendIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqAddFriendIPC& default_instance();

  static inline const ReqAddFriendIPC* internal_default_instance() {
    return reinterpret_cast<const ReqAddFriendIPC*>(
               &_ReqAddFriendIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ReqAddFriendIPC* other);

  // implements Message ----------------------------------------------

  inline ReqAddFriendIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ReqAddFriendIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReqAddFriendIPC& from);
  void MergeFrom(const ReqAddFriendIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReqAddFriendIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 arid = 2;
  void clear_arid();
  static const int kAridFieldNumber = 2;
  ::google::protobuf::int32 arid() const;
  void set_arid(::google::protobuf::int32 value);

  // int32 requestId = 3;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 3;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ReqAddFriendIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 arid_;
  ::google::protobuf::int32 requestid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResAddFriendIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ResAddFriendIPC) */ {
 public:
  ResAddFriendIPC();
  virtual ~ResAddFriendIPC();

  ResAddFriendIPC(const ResAddFriendIPC& from);

  inline ResAddFriendIPC& operator=(const ResAddFriendIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResAddFriendIPC& default_instance();

  static inline const ResAddFriendIPC* internal_default_instance() {
    return reinterpret_cast<const ResAddFriendIPC*>(
               &_ResAddFriendIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(ResAddFriendIPC* other);

  // implements Message ----------------------------------------------

  inline ResAddFriendIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ResAddFriendIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResAddFriendIPC& from);
  void MergeFrom(const ResAddFriendIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResAddFriendIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .inner_ipc.FriendItem friend = 4;
  bool has_friend_() const;
  void clear_friend_();
  static const int kFriendFieldNumber = 4;
  const ::inner_ipc::FriendItem& friend_() const;
  ::inner_ipc::FriendItem* mutable_friend_();
  ::inner_ipc::FriendItem* release_friend_();
  void set_allocated_friend_(::inner_ipc::FriendItem* friend_);

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 2;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // int32 status = 3;
  void clear_status();
  static const int kStatusFieldNumber = 3;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ResAddFriendIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::inner_ipc::FriendItem* friend__;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  ::google::protobuf::int32 status_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OfflineMsgItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.OfflineMsgItem) */ {
 public:
  OfflineMsgItem();
  virtual ~OfflineMsgItem();

  OfflineMsgItem(const OfflineMsgItem& from);

  inline OfflineMsgItem& operator=(const OfflineMsgItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OfflineMsgItem& default_instance();

  static inline const OfflineMsgItem* internal_default_instance() {
    return reinterpret_cast<const OfflineMsgItem*>(
               &_OfflineMsgItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(OfflineMsgItem* other);

  // implements Message ----------------------------------------------

  inline OfflineMsgItem* New() const PROTOBUF_FINAL { return New(NULL); }

  OfflineMsgItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OfflineMsgItem& from);
  void MergeFrom(const OfflineMsgItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OfflineMsgItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 8;
  void clear_msg();
  static const int kMsgFieldNumber = 8;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // string sname = 9;
  void clear_sname();
  static const int kSnameFieldNumber = 9;
  const ::std::string& sname() const;
  void set_sname(const ::std::string& value);
  #if LANG_CXX11
  void set_sname(::std::string&& value);
  #endif
  void set_sname(const char* value);
  void set_sname(const char* value, size_t size);
  ::std::string* mutable_sname();
  ::std::string* release_sname();
  void set_allocated_sname(::std::string* sname);

  // int32 srid = 1;
  void clear_srid();
  static const int kSridFieldNumber = 1;
  ::google::protobuf::int32 srid() const;
  void set_srid(::google::protobuf::int32 value);

  // int32 did = 2;
  void clear_did();
  static const int kDidFieldNumber = 2;
  ::google::protobuf::int32 did() const;
  void set_did(::google::protobuf::int32 value);

  // int32 type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 msg_type = 4;
  void clear_msg_type();
  static const int kMsgTypeFieldNumber = 4;
  ::google::protobuf::int32 msg_type() const;
  void set_msg_type(::google::protobuf::int32 value);

  // int32 tid = 5;
  void clear_tid();
  static const int kTidFieldNumber = 5;
  ::google::protobuf::int32 tid() const;
  void set_tid(::google::protobuf::int32 value);

  // int32 msg_size = 6;
  void clear_msg_size();
  static const int kMsgSizeFieldNumber = 6;
  ::google::protobuf::int32 msg_size() const;
  void set_msg_size(::google::protobuf::int32 value);

  // int32 stime = 7;
  void clear_stime();
  static const int kStimeFieldNumber = 7;
  ::google::protobuf::int32 stime() const;
  void set_stime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.OfflineMsgItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::internal::ArenaStringPtr sname_;
  ::google::protobuf::int32 srid_;
  ::google::protobuf::int32 did_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 msg_type_;
  ::google::protobuf::int32 tid_;
  ::google::protobuf::int32 msg_size_;
  ::google::protobuf::int32 stime_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqOfflineMsgIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ReqOfflineMsgIPC) */ {
 public:
  ReqOfflineMsgIPC();
  virtual ~ReqOfflineMsgIPC();

  ReqOfflineMsgIPC(const ReqOfflineMsgIPC& from);

  inline ReqOfflineMsgIPC& operator=(const ReqOfflineMsgIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqOfflineMsgIPC& default_instance();

  static inline const ReqOfflineMsgIPC* internal_default_instance() {
    return reinterpret_cast<const ReqOfflineMsgIPC*>(
               &_ReqOfflineMsgIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(ReqOfflineMsgIPC* other);

  // implements Message ----------------------------------------------

  inline ReqOfflineMsgIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ReqOfflineMsgIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReqOfflineMsgIPC& from);
  void MergeFrom(const ReqOfflineMsgIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReqOfflineMsgIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 rrid = 3;
  void clear_rrid();
  static const int kRridFieldNumber = 3;
  ::google::protobuf::int32 rrid() const;
  void set_rrid(::google::protobuf::int32 value);

  // int32 count = 4;
  void clear_count();
  static const int kCountFieldNumber = 4;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // int32 requestId = 5;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 5;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ReqOfflineMsgIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 rrid_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 requestid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResOfflineMsgIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ResOfflineMsgIPC) */ {
 public:
  ResOfflineMsgIPC();
  virtual ~ResOfflineMsgIPC();

  ResOfflineMsgIPC(const ResOfflineMsgIPC& from);

  inline ResOfflineMsgIPC& operator=(const ResOfflineMsgIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResOfflineMsgIPC& default_instance();

  static inline const ResOfflineMsgIPC* internal_default_instance() {
    return reinterpret_cast<const ResOfflineMsgIPC*>(
               &_ResOfflineMsgIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(ResOfflineMsgIPC* other);

  // implements Message ----------------------------------------------

  inline ResOfflineMsgIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ResOfflineMsgIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResOfflineMsgIPC& from);
  void MergeFrom(const ResOfflineMsgIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResOfflineMsgIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .inner_ipc.OfflineMsgItem msgs = 4;
  int msgs_size() const;
  void clear_msgs();
  static const int kMsgsFieldNumber = 4;
  const ::inner_ipc::OfflineMsgItem& msgs(int index) const;
  ::inner_ipc::OfflineMsgItem* mutable_msgs(int index);
  ::inner_ipc::OfflineMsgItem* add_msgs();
  ::google::protobuf::RepeatedPtrField< ::inner_ipc::OfflineMsgItem >*
      mutable_msgs();
  const ::google::protobuf::RepeatedPtrField< ::inner_ipc::OfflineMsgItem >&
      msgs() const;

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 2;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 2;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // int32 count = 3;
  void clear_count();
  static const int kCountFieldNumber = 3;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ResOfflineMsgIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::inner_ipc::OfflineMsgItem > msgs_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  ::google::protobuf::int32 count_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fdb_5fipc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RoleInfo

// int32 rid = 2;
inline void RoleInfo::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 RoleInfo::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.RoleInfo.rid)
  return rid_;
}
inline void RoleInfo::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.RoleInfo.rid)
}

// string name = 3;
inline void RoleInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoleInfo::name() const {
  // @@protoc_insertion_point(field_get:inner_ipc.RoleInfo.name)
  return name_.GetNoArena();
}
inline void RoleInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.RoleInfo.name)
}
#if LANG_CXX11
inline void RoleInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.RoleInfo.name)
}
#endif
inline void RoleInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.RoleInfo.name)
}
inline void RoleInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.RoleInfo.name)
}
inline ::std::string* RoleInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.RoleInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoleInfo::release_name() {
  // @@protoc_insertion_point(field_release:inner_ipc.RoleInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoleInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.RoleInfo.name)
}

// -------------------------------------------------------------------

// LoginInfo

// int32 rid = 1;
inline void LoginInfo::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 LoginInfo::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.LoginInfo.rid)
  return rid_;
}
inline void LoginInfo::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.LoginInfo.rid)
}

// -------------------------------------------------------------------

// ReqRoleInfoIPC

// int32 rid = 1;
inline void ReqRoleInfoIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ReqRoleInfoIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqRoleInfoIPC.rid)
  return rid_;
}
inline void ReqRoleInfoIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqRoleInfoIPC.rid)
}

// int32 requestId = 2;
inline void ReqRoleInfoIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ReqRoleInfoIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqRoleInfoIPC.requestId)
  return requestid_;
}
inline void ReqRoleInfoIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqRoleInfoIPC.requestId)
}

// int32 reqrid = 3;
inline void ReqRoleInfoIPC::clear_reqrid() {
  reqrid_ = 0;
}
inline ::google::protobuf::int32 ReqRoleInfoIPC::reqrid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqRoleInfoIPC.reqrid)
  return reqrid_;
}
inline void ReqRoleInfoIPC::set_reqrid(::google::protobuf::int32 value) {
  
  reqrid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqRoleInfoIPC.reqrid)
}

// -------------------------------------------------------------------

// ResRoleInfoIPC

// int32 rid = 1;
inline void ResRoleInfoIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ResRoleInfoIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResRoleInfoIPC.rid)
  return rid_;
}
inline void ResRoleInfoIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResRoleInfoIPC.rid)
}

// int32 requestId = 2;
inline void ResRoleInfoIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ResRoleInfoIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResRoleInfoIPC.requestId)
  return requestid_;
}
inline void ResRoleInfoIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResRoleInfoIPC.requestId)
}

// int32 reqrid = 3;
inline void ResRoleInfoIPC::clear_reqrid() {
  reqrid_ = 0;
}
inline ::google::protobuf::int32 ResRoleInfoIPC::reqrid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResRoleInfoIPC.reqrid)
  return reqrid_;
}
inline void ResRoleInfoIPC::set_reqrid(::google::protobuf::int32 value) {
  
  reqrid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResRoleInfoIPC.reqrid)
}

// .inner_ipc.RoleInfo info = 4;
inline bool ResRoleInfoIPC::has_info() const {
  return this != internal_default_instance() && info_ != NULL;
}
inline void ResRoleInfoIPC::clear_info() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) delete info_;
  info_ = NULL;
}
inline const ::inner_ipc::RoleInfo& ResRoleInfoIPC::info() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResRoleInfoIPC.info)
  return info_ != NULL ? *info_
                         : *::inner_ipc::RoleInfo::internal_default_instance();
}
inline ::inner_ipc::RoleInfo* ResRoleInfoIPC::mutable_info() {
  
  if (info_ == NULL) {
    info_ = new ::inner_ipc::RoleInfo;
  }
  // @@protoc_insertion_point(field_mutable:inner_ipc.ResRoleInfoIPC.info)
  return info_;
}
inline ::inner_ipc::RoleInfo* ResRoleInfoIPC::release_info() {
  // @@protoc_insertion_point(field_release:inner_ipc.ResRoleInfoIPC.info)
  
  ::inner_ipc::RoleInfo* temp = info_;
  info_ = NULL;
  return temp;
}
inline void ResRoleInfoIPC::set_allocated_info(::inner_ipc::RoleInfo* info) {
  delete info_;
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.ResRoleInfoIPC.info)
}

// string name = 5;
inline void ResRoleInfoIPC::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResRoleInfoIPC::name() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResRoleInfoIPC.name)
  return name_.GetNoArena();
}
inline void ResRoleInfoIPC::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.ResRoleInfoIPC.name)
}
#if LANG_CXX11
inline void ResRoleInfoIPC::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.ResRoleInfoIPC.name)
}
#endif
inline void ResRoleInfoIPC::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.ResRoleInfoIPC.name)
}
inline void ResRoleInfoIPC::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.ResRoleInfoIPC.name)
}
inline ::std::string* ResRoleInfoIPC::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.ResRoleInfoIPC.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResRoleInfoIPC::release_name() {
  // @@protoc_insertion_point(field_release:inner_ipc.ResRoleInfoIPC.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResRoleInfoIPC::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.ResRoleInfoIPC.name)
}

// -------------------------------------------------------------------

// FriendItem

// int32 rid = 1;
inline void FriendItem::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 FriendItem::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.FriendItem.rid)
  return rid_;
}
inline void FriendItem::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.FriendItem.rid)
}

// int32 status = 2;
inline void FriendItem::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 FriendItem::status() const {
  // @@protoc_insertion_point(field_get:inner_ipc.FriendItem.status)
  return status_;
}
inline void FriendItem::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.FriendItem.status)
}

// int32 timeline = 3;
inline void FriendItem::clear_timeline() {
  timeline_ = 0;
}
inline ::google::protobuf::int32 FriendItem::timeline() const {
  // @@protoc_insertion_point(field_get:inner_ipc.FriendItem.timeline)
  return timeline_;
}
inline void FriendItem::set_timeline(::google::protobuf::int32 value) {
  
  timeline_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.FriendItem.timeline)
}

// string username = 4;
inline void FriendItem::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FriendItem::username() const {
  // @@protoc_insertion_point(field_get:inner_ipc.FriendItem.username)
  return username_.GetNoArena();
}
inline void FriendItem::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.FriendItem.username)
}
#if LANG_CXX11
inline void FriendItem::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.FriendItem.username)
}
#endif
inline void FriendItem::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.FriendItem.username)
}
inline void FriendItem::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.FriendItem.username)
}
inline ::std::string* FriendItem::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.FriendItem.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FriendItem::release_username() {
  // @@protoc_insertion_point(field_release:inner_ipc.FriendItem.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FriendItem::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.FriendItem.username)
}

// -------------------------------------------------------------------

// ReqFriendsIPC

// int32 rid = 1;
inline void ReqFriendsIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ReqFriendsIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqFriendsIPC.rid)
  return rid_;
}
inline void ReqFriendsIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqFriendsIPC.rid)
}

// int32 requestId = 2;
inline void ReqFriendsIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ReqFriendsIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqFriendsIPC.requestId)
  return requestid_;
}
inline void ReqFriendsIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqFriendsIPC.requestId)
}

// int32 type = 3;
inline void ReqFriendsIPC::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ReqFriendsIPC::type() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqFriendsIPC.type)
  return type_;
}
inline void ReqFriendsIPC::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqFriendsIPC.type)
}

// -------------------------------------------------------------------

// ResFriendsIPC

// int32 rid = 1;
inline void ResFriendsIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ResFriendsIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResFriendsIPC.rid)
  return rid_;
}
inline void ResFriendsIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResFriendsIPC.rid)
}

// int32 requestId = 2;
inline void ResFriendsIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ResFriendsIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResFriendsIPC.requestId)
  return requestid_;
}
inline void ResFriendsIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResFriendsIPC.requestId)
}

// repeated .inner_ipc.FriendItem friends = 3;
inline int ResFriendsIPC::friends_size() const {
  return friends_.size();
}
inline void ResFriendsIPC::clear_friends() {
  friends_.Clear();
}
inline const ::inner_ipc::FriendItem& ResFriendsIPC::friends(int index) const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResFriendsIPC.friends)
  return friends_.Get(index);
}
inline ::inner_ipc::FriendItem* ResFriendsIPC::mutable_friends(int index) {
  // @@protoc_insertion_point(field_mutable:inner_ipc.ResFriendsIPC.friends)
  return friends_.Mutable(index);
}
inline ::inner_ipc::FriendItem* ResFriendsIPC::add_friends() {
  // @@protoc_insertion_point(field_add:inner_ipc.ResFriendsIPC.friends)
  return friends_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::inner_ipc::FriendItem >*
ResFriendsIPC::mutable_friends() {
  // @@protoc_insertion_point(field_mutable_list:inner_ipc.ResFriendsIPC.friends)
  return &friends_;
}
inline const ::google::protobuf::RepeatedPtrField< ::inner_ipc::FriendItem >&
ResFriendsIPC::friends() const {
  // @@protoc_insertion_point(field_list:inner_ipc.ResFriendsIPC.friends)
  return friends_;
}

// -------------------------------------------------------------------

// ReqAddFriendIPC

// int32 rid = 1;
inline void ReqAddFriendIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ReqAddFriendIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqAddFriendIPC.rid)
  return rid_;
}
inline void ReqAddFriendIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqAddFriendIPC.rid)
}

// int32 arid = 2;
inline void ReqAddFriendIPC::clear_arid() {
  arid_ = 0;
}
inline ::google::protobuf::int32 ReqAddFriendIPC::arid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqAddFriendIPC.arid)
  return arid_;
}
inline void ReqAddFriendIPC::set_arid(::google::protobuf::int32 value) {
  
  arid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqAddFriendIPC.arid)
}

// int32 requestId = 3;
inline void ReqAddFriendIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ReqAddFriendIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqAddFriendIPC.requestId)
  return requestid_;
}
inline void ReqAddFriendIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqAddFriendIPC.requestId)
}

// -------------------------------------------------------------------

// ResAddFriendIPC

// int32 rid = 1;
inline void ResAddFriendIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ResAddFriendIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResAddFriendIPC.rid)
  return rid_;
}
inline void ResAddFriendIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResAddFriendIPC.rid)
}

// int32 requestId = 2;
inline void ResAddFriendIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ResAddFriendIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResAddFriendIPC.requestId)
  return requestid_;
}
inline void ResAddFriendIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResAddFriendIPC.requestId)
}

// int32 status = 3;
inline void ResAddFriendIPC::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 ResAddFriendIPC::status() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResAddFriendIPC.status)
  return status_;
}
inline void ResAddFriendIPC::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResAddFriendIPC.status)
}

// .inner_ipc.FriendItem friend = 4;
inline bool ResAddFriendIPC::has_friend_() const {
  return this != internal_default_instance() && friend__ != NULL;
}
inline void ResAddFriendIPC::clear_friend_() {
  if (GetArenaNoVirtual() == NULL && friend__ != NULL) delete friend__;
  friend__ = NULL;
}
inline const ::inner_ipc::FriendItem& ResAddFriendIPC::friend_() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResAddFriendIPC.friend)
  return friend__ != NULL ? *friend__
                         : *::inner_ipc::FriendItem::internal_default_instance();
}
inline ::inner_ipc::FriendItem* ResAddFriendIPC::mutable_friend_() {
  
  if (friend__ == NULL) {
    friend__ = new ::inner_ipc::FriendItem;
  }
  // @@protoc_insertion_point(field_mutable:inner_ipc.ResAddFriendIPC.friend)
  return friend__;
}
inline ::inner_ipc::FriendItem* ResAddFriendIPC::release_friend_() {
  // @@protoc_insertion_point(field_release:inner_ipc.ResAddFriendIPC.friend)
  
  ::inner_ipc::FriendItem* temp = friend__;
  friend__ = NULL;
  return temp;
}
inline void ResAddFriendIPC::set_allocated_friend_(::inner_ipc::FriendItem* friend_) {
  delete friend__;
  friend__ = friend_;
  if (friend_) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.ResAddFriendIPC.friend)
}

// -------------------------------------------------------------------

// OfflineMsgItem

// int32 srid = 1;
inline void OfflineMsgItem::clear_srid() {
  srid_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::srid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.srid)
  return srid_;
}
inline void OfflineMsgItem::set_srid(::google::protobuf::int32 value) {
  
  srid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.srid)
}

// int32 did = 2;
inline void OfflineMsgItem::clear_did() {
  did_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::did() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.did)
  return did_;
}
inline void OfflineMsgItem::set_did(::google::protobuf::int32 value) {
  
  did_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.did)
}

// int32 type = 3;
inline void OfflineMsgItem::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::type() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.type)
  return type_;
}
inline void OfflineMsgItem::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.type)
}

// int32 msg_type = 4;
inline void OfflineMsgItem::clear_msg_type() {
  msg_type_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::msg_type() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.msg_type)
  return msg_type_;
}
inline void OfflineMsgItem::set_msg_type(::google::protobuf::int32 value) {
  
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.msg_type)
}

// int32 tid = 5;
inline void OfflineMsgItem::clear_tid() {
  tid_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::tid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.tid)
  return tid_;
}
inline void OfflineMsgItem::set_tid(::google::protobuf::int32 value) {
  
  tid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.tid)
}

// int32 msg_size = 6;
inline void OfflineMsgItem::clear_msg_size() {
  msg_size_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::msg_size() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.msg_size)
  return msg_size_;
}
inline void OfflineMsgItem::set_msg_size(::google::protobuf::int32 value) {
  
  msg_size_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.msg_size)
}

// int32 stime = 7;
inline void OfflineMsgItem::clear_stime() {
  stime_ = 0;
}
inline ::google::protobuf::int32 OfflineMsgItem::stime() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.stime)
  return stime_;
}
inline void OfflineMsgItem::set_stime(::google::protobuf::int32 value) {
  
  stime_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.stime)
}

// string msg = 8;
inline void OfflineMsgItem::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OfflineMsgItem::msg() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.msg)
  return msg_.GetNoArena();
}
inline void OfflineMsgItem::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.msg)
}
#if LANG_CXX11
inline void OfflineMsgItem::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.OfflineMsgItem.msg)
}
#endif
inline void OfflineMsgItem::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.OfflineMsgItem.msg)
}
inline void OfflineMsgItem::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.OfflineMsgItem.msg)
}
inline ::std::string* OfflineMsgItem::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.OfflineMsgItem.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OfflineMsgItem::release_msg() {
  // @@protoc_insertion_point(field_release:inner_ipc.OfflineMsgItem.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OfflineMsgItem::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.OfflineMsgItem.msg)
}

// string sname = 9;
inline void OfflineMsgItem::clear_sname() {
  sname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OfflineMsgItem::sname() const {
  // @@protoc_insertion_point(field_get:inner_ipc.OfflineMsgItem.sname)
  return sname_.GetNoArena();
}
inline void OfflineMsgItem::set_sname(const ::std::string& value) {
  
  sname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.OfflineMsgItem.sname)
}
#if LANG_CXX11
inline void OfflineMsgItem::set_sname(::std::string&& value) {
  
  sname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.OfflineMsgItem.sname)
}
#endif
inline void OfflineMsgItem::set_sname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.OfflineMsgItem.sname)
}
inline void OfflineMsgItem::set_sname(const char* value, size_t size) {
  
  sname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.OfflineMsgItem.sname)
}
inline ::std::string* OfflineMsgItem::mutable_sname() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.OfflineMsgItem.sname)
  return sname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OfflineMsgItem::release_sname() {
  // @@protoc_insertion_point(field_release:inner_ipc.OfflineMsgItem.sname)
  
  return sname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OfflineMsgItem::set_allocated_sname(::std::string* sname) {
  if (sname != NULL) {
    
  } else {
    
  }
  sname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sname);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.OfflineMsgItem.sname)
}

// -------------------------------------------------------------------

// ReqOfflineMsgIPC

// int32 rid = 1;
inline void ReqOfflineMsgIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ReqOfflineMsgIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqOfflineMsgIPC.rid)
  return rid_;
}
inline void ReqOfflineMsgIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqOfflineMsgIPC.rid)
}

// int32 type = 2;
inline void ReqOfflineMsgIPC::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ReqOfflineMsgIPC::type() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqOfflineMsgIPC.type)
  return type_;
}
inline void ReqOfflineMsgIPC::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqOfflineMsgIPC.type)
}

// int32 rrid = 3;
inline void ReqOfflineMsgIPC::clear_rrid() {
  rrid_ = 0;
}
inline ::google::protobuf::int32 ReqOfflineMsgIPC::rrid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqOfflineMsgIPC.rrid)
  return rrid_;
}
inline void ReqOfflineMsgIPC::set_rrid(::google::protobuf::int32 value) {
  
  rrid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqOfflineMsgIPC.rrid)
}

// int32 count = 4;
inline void ReqOfflineMsgIPC::clear_count() {
  count_ = 0;
}
inline ::google::protobuf::int32 ReqOfflineMsgIPC::count() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqOfflineMsgIPC.count)
  return count_;
}
inline void ReqOfflineMsgIPC::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqOfflineMsgIPC.count)
}

// int32 requestId = 5;
inline void ReqOfflineMsgIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ReqOfflineMsgIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReqOfflineMsgIPC.requestId)
  return requestid_;
}
inline void ReqOfflineMsgIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReqOfflineMsgIPC.requestId)
}

// -------------------------------------------------------------------

// ResOfflineMsgIPC

// int32 rid = 1;
inline void ResOfflineMsgIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ResOfflineMsgIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResOfflineMsgIPC.rid)
  return rid_;
}
inline void ResOfflineMsgIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResOfflineMsgIPC.rid)
}

// int32 requestId = 2;
inline void ResOfflineMsgIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 ResOfflineMsgIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResOfflineMsgIPC.requestId)
  return requestid_;
}
inline void ResOfflineMsgIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResOfflineMsgIPC.requestId)
}

// int32 count = 3;
inline void ResOfflineMsgIPC::clear_count() {
  count_ = 0;
}
inline ::google::protobuf::int32 ResOfflineMsgIPC::count() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResOfflineMsgIPC.count)
  return count_;
}
inline void ResOfflineMsgIPC::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ResOfflineMsgIPC.count)
}

// repeated .inner_ipc.OfflineMsgItem msgs = 4;
inline int ResOfflineMsgIPC::msgs_size() const {
  return msgs_.size();
}
inline void ResOfflineMsgIPC::clear_msgs() {
  msgs_.Clear();
}
inline const ::inner_ipc::OfflineMsgItem& ResOfflineMsgIPC::msgs(int index) const {
  // @@protoc_insertion_point(field_get:inner_ipc.ResOfflineMsgIPC.msgs)
  return msgs_.Get(index);
}
inline ::inner_ipc::OfflineMsgItem* ResOfflineMsgIPC::mutable_msgs(int index) {
  // @@protoc_insertion_point(field_mutable:inner_ipc.ResOfflineMsgIPC.msgs)
  return msgs_.Mutable(index);
}
inline ::inner_ipc::OfflineMsgItem* ResOfflineMsgIPC::add_msgs() {
  // @@protoc_insertion_point(field_add:inner_ipc.ResOfflineMsgIPC.msgs)
  return msgs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::inner_ipc::OfflineMsgItem >*
ResOfflineMsgIPC::mutable_msgs() {
  // @@protoc_insertion_point(field_mutable_list:inner_ipc.ResOfflineMsgIPC.msgs)
  return &msgs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::inner_ipc::OfflineMsgItem >&
ResOfflineMsgIPC::msgs() const {
  // @@protoc_insertion_point(field_list:inner_ipc.ResOfflineMsgIPC.msgs)
  return msgs_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace inner_ipc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gs_5fdb_5fipc_2eproto__INCLUDED
