// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gs_gw_ipc.proto

#ifndef PROTOBUF_gs_5fgw_5fipc_2eproto__INCLUDED
#define PROTOBUF_gs_5fgw_5fipc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace inner_ipc {
class DisconnectIPC;
class DisconnectIPCDefaultTypeInternal;
extern DisconnectIPCDefaultTypeInternal _DisconnectIPC_default_instance_;
class EnterGameIPC;
class EnterGameIPCDefaultTypeInternal;
extern EnterGameIPCDefaultTypeInternal _EnterGameIPC_default_instance_;
class ExitGameIPC;
class ExitGameIPCDefaultTypeInternal;
extern ExitGameIPCDefaultTypeInternal _ExitGameIPC_default_instance_;
class ReConnectIPC;
class ReConnectIPCDefaultTypeInternal;
extern ReConnectIPCDefaultTypeInternal _ReConnectIPC_default_instance_;
class RequestRolesIPC;
class RequestRolesIPCDefaultTypeInternal;
extern RequestRolesIPCDefaultTypeInternal _RequestRolesIPC_default_instance_;
}  // namespace inner_ipc

namespace inner_ipc {

namespace protobuf_gs_5fgw_5fipc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gs_5fgw_5fipc_2eproto

// ===================================================================

class EnterGameIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.EnterGameIPC) */ {
 public:
  EnterGameIPC();
  virtual ~EnterGameIPC();

  EnterGameIPC(const EnterGameIPC& from);

  inline EnterGameIPC& operator=(const EnterGameIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnterGameIPC& default_instance();

  static inline const EnterGameIPC* internal_default_instance() {
    return reinterpret_cast<const EnterGameIPC*>(
               &_EnterGameIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(EnterGameIPC* other);

  // implements Message ----------------------------------------------

  inline EnterGameIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  EnterGameIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EnterGameIPC& from);
  void MergeFrom(const EnterGameIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EnterGameIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.EnterGameIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fgw_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ExitGameIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ExitGameIPC) */ {
 public:
  ExitGameIPC();
  virtual ~ExitGameIPC();

  ExitGameIPC(const ExitGameIPC& from);

  inline ExitGameIPC& operator=(const ExitGameIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExitGameIPC& default_instance();

  static inline const ExitGameIPC* internal_default_instance() {
    return reinterpret_cast<const ExitGameIPC*>(
               &_ExitGameIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ExitGameIPC* other);

  // implements Message ----------------------------------------------

  inline ExitGameIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ExitGameIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ExitGameIPC& from);
  void MergeFrom(const ExitGameIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ExitGameIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ExitGameIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fgw_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DisconnectIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.DisconnectIPC) */ {
 public:
  DisconnectIPC();
  virtual ~DisconnectIPC();

  DisconnectIPC(const DisconnectIPC& from);

  inline DisconnectIPC& operator=(const DisconnectIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DisconnectIPC& default_instance();

  static inline const DisconnectIPC* internal_default_instance() {
    return reinterpret_cast<const DisconnectIPC*>(
               &_DisconnectIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(DisconnectIPC* other);

  // implements Message ----------------------------------------------

  inline DisconnectIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  DisconnectIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DisconnectIPC& from);
  void MergeFrom(const DisconnectIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DisconnectIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.DisconnectIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fgw_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReConnectIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.ReConnectIPC) */ {
 public:
  ReConnectIPC();
  virtual ~ReConnectIPC();

  ReConnectIPC(const ReConnectIPC& from);

  inline ReConnectIPC& operator=(const ReConnectIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReConnectIPC& default_instance();

  static inline const ReConnectIPC* internal_default_instance() {
    return reinterpret_cast<const ReConnectIPC*>(
               &_ReConnectIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ReConnectIPC* other);

  // implements Message ----------------------------------------------

  inline ReConnectIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  ReConnectIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReConnectIPC& from);
  void MergeFrom(const ReConnectIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReConnectIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 rid = 1;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.ReConnectIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 rid_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fgw_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RequestRolesIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.RequestRolesIPC) */ {
 public:
  RequestRolesIPC();
  virtual ~RequestRolesIPC();

  RequestRolesIPC(const RequestRolesIPC& from);

  inline RequestRolesIPC& operator=(const RequestRolesIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestRolesIPC& default_instance();

  static inline const RequestRolesIPC* internal_default_instance() {
    return reinterpret_cast<const RequestRolesIPC*>(
               &_RequestRolesIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RequestRolesIPC* other);

  // implements Message ----------------------------------------------

  inline RequestRolesIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  RequestRolesIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RequestRolesIPC& from);
  void MergeFrom(const RequestRolesIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RequestRolesIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .inner_ipc.ReConnectIPC ipc = 1;
  int ipc_size() const;
  void clear_ipc();
  static const int kIpcFieldNumber = 1;
  const ::inner_ipc::ReConnectIPC& ipc(int index) const;
  ::inner_ipc::ReConnectIPC* mutable_ipc(int index);
  ::inner_ipc::ReConnectIPC* add_ipc();
  ::google::protobuf::RepeatedPtrField< ::inner_ipc::ReConnectIPC >*
      mutable_ipc();
  const ::google::protobuf::RepeatedPtrField< ::inner_ipc::ReConnectIPC >&
      ipc() const;

  // @@protoc_insertion_point(class_scope:inner_ipc.RequestRolesIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::inner_ipc::ReConnectIPC > ipc_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5fgw_5fipc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// EnterGameIPC

// int32 rid = 1;
inline void EnterGameIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 EnterGameIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.EnterGameIPC.rid)
  return rid_;
}
inline void EnterGameIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.EnterGameIPC.rid)
}

// -------------------------------------------------------------------

// ExitGameIPC

// int32 rid = 1;
inline void ExitGameIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ExitGameIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ExitGameIPC.rid)
  return rid_;
}
inline void ExitGameIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ExitGameIPC.rid)
}

// -------------------------------------------------------------------

// DisconnectIPC

// int32 rid = 1;
inline void DisconnectIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 DisconnectIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.DisconnectIPC.rid)
  return rid_;
}
inline void DisconnectIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.DisconnectIPC.rid)
}

// -------------------------------------------------------------------

// ReConnectIPC

// int32 rid = 1;
inline void ReConnectIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 ReConnectIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.ReConnectIPC.rid)
  return rid_;
}
inline void ReConnectIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.ReConnectIPC.rid)
}

// -------------------------------------------------------------------

// RequestRolesIPC

// repeated .inner_ipc.ReConnectIPC ipc = 1;
inline int RequestRolesIPC::ipc_size() const {
  return ipc_.size();
}
inline void RequestRolesIPC::clear_ipc() {
  ipc_.Clear();
}
inline const ::inner_ipc::ReConnectIPC& RequestRolesIPC::ipc(int index) const {
  // @@protoc_insertion_point(field_get:inner_ipc.RequestRolesIPC.ipc)
  return ipc_.Get(index);
}
inline ::inner_ipc::ReConnectIPC* RequestRolesIPC::mutable_ipc(int index) {
  // @@protoc_insertion_point(field_mutable:inner_ipc.RequestRolesIPC.ipc)
  return ipc_.Mutable(index);
}
inline ::inner_ipc::ReConnectIPC* RequestRolesIPC::add_ipc() {
  // @@protoc_insertion_point(field_add:inner_ipc.RequestRolesIPC.ipc)
  return ipc_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::inner_ipc::ReConnectIPC >*
RequestRolesIPC::mutable_ipc() {
  // @@protoc_insertion_point(field_mutable_list:inner_ipc.RequestRolesIPC.ipc)
  return &ipc_;
}
inline const ::google::protobuf::RepeatedPtrField< ::inner_ipc::ReConnectIPC >&
RequestRolesIPC::ipc() const {
  // @@protoc_insertion_point(field_list:inner_ipc.RequestRolesIPC.ipc)
  return ipc_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace inner_ipc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gs_5fgw_5fipc_2eproto__INCLUDED
