// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gy_login_ipc.proto

#ifndef PROTOBUF_gy_5flogin_5fipc_2eproto__INCLUDED
#define PROTOBUF_gy_5flogin_5fipc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace inner_ipc {
class Gateway2LoginIPC;
class Gateway2LoginIPCDefaultTypeInternal;
extern Gateway2LoginIPCDefaultTypeInternal _Gateway2LoginIPC_default_instance_;
class Login2GatewayIPC;
class Login2GatewayIPCDefaultTypeInternal;
extern Login2GatewayIPCDefaultTypeInternal _Login2GatewayIPC_default_instance_;
}  // namespace inner_ipc

namespace inner_ipc {

namespace protobuf_gy_5flogin_5fipc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gy_5flogin_5fipc_2eproto

// ===================================================================

class Gateway2LoginIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.Gateway2LoginIPC) */ {
 public:
  Gateway2LoginIPC();
  virtual ~Gateway2LoginIPC();

  Gateway2LoginIPC(const Gateway2LoginIPC& from);

  inline Gateway2LoginIPC& operator=(const Gateway2LoginIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Gateway2LoginIPC& default_instance();

  static inline const Gateway2LoginIPC* internal_default_instance() {
    return reinterpret_cast<const Gateway2LoginIPC*>(
               &_Gateway2LoginIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Gateway2LoginIPC* other);

  // implements Message ----------------------------------------------

  inline Gateway2LoginIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  Gateway2LoginIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Gateway2LoginIPC& from);
  void MergeFrom(const Gateway2LoginIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Gateway2LoginIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string userName = 2;
  void clear_username();
  static const int kUserNameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // uint32 requestId = 1;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 1;
  ::google::protobuf::uint32 requestid() const;
  void set_requestid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.Gateway2LoginIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::uint32 requestid_;
  mutable int _cached_size_;
  friend struct protobuf_gy_5flogin_5fipc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Login2GatewayIPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inner_ipc.Login2GatewayIPC) */ {
 public:
  Login2GatewayIPC();
  virtual ~Login2GatewayIPC();

  Login2GatewayIPC(const Login2GatewayIPC& from);

  inline Login2GatewayIPC& operator=(const Login2GatewayIPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login2GatewayIPC& default_instance();

  static inline const Login2GatewayIPC* internal_default_instance() {
    return reinterpret_cast<const Login2GatewayIPC*>(
               &_Login2GatewayIPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Login2GatewayIPC* other);

  // implements Message ----------------------------------------------

  inline Login2GatewayIPC* New() const PROTOBUF_FINAL { return New(NULL); }

  Login2GatewayIPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Login2GatewayIPC& from);
  void MergeFrom(const Login2GatewayIPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Login2GatewayIPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 5;
  void clear_key();
  static const int kKeyFieldNumber = 5;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string msg = 6;
  void clear_msg();
  static const int kMsgFieldNumber = 6;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // string address = 7;
  void clear_address();
  static const int kAddressFieldNumber = 7;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // int32 port = 1;
  void clear_port();
  static const int kPortFieldNumber = 1;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // int32 rid = 2;
  void clear_rid();
  static const int kRidFieldNumber = 2;
  ::google::protobuf::int32 rid() const;
  void set_rid(::google::protobuf::int32 value);

  // int32 requestId = 3;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 3;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // int32 status = 4;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:inner_ipc.Login2GatewayIPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::int32 rid_;
  ::google::protobuf::int32 requestid_;
  ::google::protobuf::int32 status_;
  mutable int _cached_size_;
  friend struct protobuf_gy_5flogin_5fipc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Gateway2LoginIPC

// uint32 requestId = 1;
inline void Gateway2LoginIPC::clear_requestid() {
  requestid_ = 0u;
}
inline ::google::protobuf::uint32 Gateway2LoginIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Gateway2LoginIPC.requestId)
  return requestid_;
}
inline void Gateway2LoginIPC::set_requestid(::google::protobuf::uint32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.Gateway2LoginIPC.requestId)
}

// string userName = 2;
inline void Gateway2LoginIPC::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Gateway2LoginIPC::username() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Gateway2LoginIPC.userName)
  return username_.GetNoArena();
}
inline void Gateway2LoginIPC::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.Gateway2LoginIPC.userName)
}
#if LANG_CXX11
inline void Gateway2LoginIPC::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.Gateway2LoginIPC.userName)
}
#endif
inline void Gateway2LoginIPC::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.Gateway2LoginIPC.userName)
}
inline void Gateway2LoginIPC::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.Gateway2LoginIPC.userName)
}
inline ::std::string* Gateway2LoginIPC::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.Gateway2LoginIPC.userName)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Gateway2LoginIPC::release_username() {
  // @@protoc_insertion_point(field_release:inner_ipc.Gateway2LoginIPC.userName)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Gateway2LoginIPC::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.Gateway2LoginIPC.userName)
}

// -------------------------------------------------------------------

// Login2GatewayIPC

// int32 port = 1;
inline void Login2GatewayIPC::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 Login2GatewayIPC::port() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.port)
  return port_;
}
inline void Login2GatewayIPC::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.port)
}

// int32 rid = 2;
inline void Login2GatewayIPC::clear_rid() {
  rid_ = 0;
}
inline ::google::protobuf::int32 Login2GatewayIPC::rid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.rid)
  return rid_;
}
inline void Login2GatewayIPC::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.rid)
}

// int32 requestId = 3;
inline void Login2GatewayIPC::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 Login2GatewayIPC::requestid() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.requestId)
  return requestid_;
}
inline void Login2GatewayIPC::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.requestId)
}

// int32 status = 4;
inline void Login2GatewayIPC::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 Login2GatewayIPC::status() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.status)
  return status_;
}
inline void Login2GatewayIPC::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.status)
}

// string key = 5;
inline void Login2GatewayIPC::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login2GatewayIPC::key() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.key)
  return key_.GetNoArena();
}
inline void Login2GatewayIPC::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.key)
}
#if LANG_CXX11
inline void Login2GatewayIPC::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.Login2GatewayIPC.key)
}
#endif
inline void Login2GatewayIPC::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.Login2GatewayIPC.key)
}
inline void Login2GatewayIPC::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.Login2GatewayIPC.key)
}
inline ::std::string* Login2GatewayIPC::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.Login2GatewayIPC.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login2GatewayIPC::release_key() {
  // @@protoc_insertion_point(field_release:inner_ipc.Login2GatewayIPC.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login2GatewayIPC::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.Login2GatewayIPC.key)
}

// string msg = 6;
inline void Login2GatewayIPC::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login2GatewayIPC::msg() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.msg)
  return msg_.GetNoArena();
}
inline void Login2GatewayIPC::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.msg)
}
#if LANG_CXX11
inline void Login2GatewayIPC::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.Login2GatewayIPC.msg)
}
#endif
inline void Login2GatewayIPC::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.Login2GatewayIPC.msg)
}
inline void Login2GatewayIPC::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.Login2GatewayIPC.msg)
}
inline ::std::string* Login2GatewayIPC::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.Login2GatewayIPC.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login2GatewayIPC::release_msg() {
  // @@protoc_insertion_point(field_release:inner_ipc.Login2GatewayIPC.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login2GatewayIPC::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.Login2GatewayIPC.msg)
}

// string address = 7;
inline void Login2GatewayIPC::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login2GatewayIPC::address() const {
  // @@protoc_insertion_point(field_get:inner_ipc.Login2GatewayIPC.address)
  return address_.GetNoArena();
}
inline void Login2GatewayIPC::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:inner_ipc.Login2GatewayIPC.address)
}
#if LANG_CXX11
inline void Login2GatewayIPC::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:inner_ipc.Login2GatewayIPC.address)
}
#endif
inline void Login2GatewayIPC::set_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:inner_ipc.Login2GatewayIPC.address)
}
inline void Login2GatewayIPC::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:inner_ipc.Login2GatewayIPC.address)
}
inline ::std::string* Login2GatewayIPC::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:inner_ipc.Login2GatewayIPC.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login2GatewayIPC::release_address() {
  // @@protoc_insertion_point(field_release:inner_ipc.Login2GatewayIPC.address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login2GatewayIPC::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:inner_ipc.Login2GatewayIPC.address)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace inner_ipc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gy_5flogin_5fipc_2eproto__INCLUDED
